version: "3.9"
services:
  firewall:
    container_name: cs-firewall
    hostname: cs-firewall
    extends:
      file: base.yml
      service: node
    networks:
      net-1:
        ipv4_address: 10.5.1.254
      net-2:
        ipv4_address: 10.5.2.254
    command: /opt/config/set-fw.sh
  host-1:
    container_name: cs-host-1
    hostname: cs-host-1
    # dns: 10.5.1.254
    extends:
      file: base.yml
      service: node
    networks:
      net-1:
        ipv4_address: 10.5.1.10
    command: /opt/config/set-gw.sh 10.5.1.254
  host-2:
    container_name: cs-host-2
    hostname: cs-host-2
    dns: 10.5.1.254
    extends:
      file: base.yml
      service: node
    networks:
      net-1:
        ipv4_address: 10.5.1.20
    command: /opt/config/set-gw.sh 10.5.1.254
  host-3:
    container_name: cs-host-3
    hostname: cs-host-3
    dns: 10.5.2.254
    extends:
      file: base.yml
      service: node
    networks:
      net-2:
        ipv4_address: 10.5.2.11
    command: /opt/config/set-gw.sh 10.5.2.254
networks:
  net-1:
    name: cs-network-1
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/24
  net-2:
    name: cs-network-2
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.2.0/24
